# Generated by Django 5.2.7 on 2025-11-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=25)),
                ('fecha_contratacion', models.CharField(max_length=15)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horario', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('puesto', models.CharField(max_length=50)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(max_length=50)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=25, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('foto_usuario', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('id_detalle_de_producto', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_Spa.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_pedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas_item', models.CharField(blank=True, max_length=255, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_Spa.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_Spa.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.IntegerField()),
                ('productos_utilizados', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='app_Spa.categorias')),
                ('empleado_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='app_Spa.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_servicio',
            fields=[
                ('id_detalle_servicio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad_usada', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='app_Spa.productos')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='app_Spa.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Reseñas',
            fields=[
                ('id_reseña', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('calificacion', models.IntegerField(default=5)),
                ('comentario', models.TextField()),
                ('fecha_reseña', models.DateTimeField(auto_now_add=True)),
                ('aprobada', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='app_Spa.productos')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseñas', to='app_Spa.servicios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='app_Spa.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_Spa.usuarios'),
        ),
    ]
