# Generated by Django 5.2.7 on 2025-11-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_pedido',
            name='notas_item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
